name: Runner
on:
  schedule:
    - cron: '4 * * * *'
    - cron: '10 * * * *'
    - cron: '15 * * * *'

jobs:
  test_shedule:
    runs-on: ubuntu-latest
    steps:
      -
        name: Calling the spider
        run: echo 'Time to crowl :)'
        
