name: Runner
on:
  schedule:
    - cron: '15 4 * * *'
    - cron: '45 12 * * *'
    - cron: '45 23 * * *'

jobs:
  test_shedule:
    runs-on: ubuntu-latest
    steps:
      -
        name: Calling the spider
        run: |
          cd /app/newsmakers/
          docker compose --env-file .env.crawl up -d
        
